// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Refundeo.Core.Data;
using System;

namespace Refundeo.Migrations
{
    [DbContext(typeof(RefundeoDbContext))]
    [Migration("20180519231129_IsOauth")]
    partial class IsOauth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.CustomerInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AcceptedPrivacyPolicy");

                    b.Property<string>("BankAccountNumber");

                    b.Property<string>("BankRegNumber");

                    b.Property<string>("Country");

                    b.Property<string>("CustomerId");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsOauth");

                    b.Property<string>("LastName");

                    b.Property<string>("PrivacyPolicy");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.ToTable("CustomerInformations");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.Documentation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Image");

                    b.HasKey("Id");

                    b.ToTable("Documentations");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.MerchantInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CVRNumber");

                    b.Property<string>("CompanyName");

                    b.Property<int>("RefundPercentage");

                    b.HasKey("Id");

                    b.ToTable("MerchantInformations");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.QRCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Image");

                    b.HasKey("Id");

                    b.ToTable("QRCodes");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.RefundCase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<long?>("CustomerInformationId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateRequested");

                    b.Property<long?>("DocumentationId");

                    b.Property<bool>("IsAccepted");

                    b.Property<bool>("IsRequested");

                    b.Property<long?>("MerchantInformationId");

                    b.Property<long?>("QRCodeId");

                    b.Property<double>("RefundAmount");

                    b.HasKey("Id");

                    b.HasIndex("CustomerInformationId");

                    b.HasIndex("DocumentationId");

                    b.HasIndex("MerchantInformationId");

                    b.HasIndex("QRCodeId");

                    b.ToTable("RefundCases");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.RefundeoUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<long?>("MerchantInformationId");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("RefreshToken");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("MerchantInformationId")
                        .IsUnique()
                        .HasFilter("[MerchantInformationId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.RefundeoUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.RefundeoUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Refundeo.Core.Data.Models.RefundeoUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.RefundeoUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.CustomerInformation", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.RefundeoUser", "Customer")
                        .WithOne("CustomerInformation")
                        .HasForeignKey("Refundeo.Core.Data.Models.CustomerInformation", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.RefundCase", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.CustomerInformation", "CustomerInformation")
                        .WithMany("RefundCases")
                        .HasForeignKey("CustomerInformationId");

                    b.HasOne("Refundeo.Core.Data.Models.Documentation", "Documentation")
                        .WithMany()
                        .HasForeignKey("DocumentationId");

                    b.HasOne("Refundeo.Core.Data.Models.MerchantInformation", "MerchantInformation")
                        .WithMany("RefundCases")
                        .HasForeignKey("MerchantInformationId");

                    b.HasOne("Refundeo.Core.Data.Models.QRCode", "QRCode")
                        .WithMany()
                        .HasForeignKey("QRCodeId");
                });

            modelBuilder.Entity("Refundeo.Core.Data.Models.RefundeoUser", b =>
                {
                    b.HasOne("Refundeo.Core.Data.Models.MerchantInformation", "MerchantInformation")
                        .WithOne("Merchant")
                        .HasForeignKey("Refundeo.Core.Data.Models.RefundeoUser", "MerchantInformationId");
                });
#pragma warning restore 612, 618
        }
    }
}
